### ISSUE TITLE
The cogito audio output has a 1-second beating artefact

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#133] opened 2017-12-26 20:28 UTC

**Comment by stephenwhitmarsh** [comment] 2017-12-26 21:01
@deep-introspection lets look at this when we meet on the 7th!

**Comment by deep-introspection** [comment] 2017-12-27 10:25
@stephenwhitmarsh Sure!

**Comment by stephenwhitmarsh** [comment] 2018-01-08 18:25
#184 It seems the beating artefact is caused by large amplitude of the electrode-position coding. Reducing the dirac seems to solve this in the offline script.

**Comment by stephenwhitmarsh** [comment] 2018-02-05 13:59
Seems to work now - closing

**Closed by stephenwhitmarsh** 2018-02-05 13:59 UTC
